# SUBBAB 7: Vectors and Vector Transposition

Topik ini membahas tentang vektor dan operasi transpose menggunakan NumPy, PyTorch, dan TensorFlow.

In [1]:
import numpy as np
import torch
import tensorflow as tf

## Soal No. 1 — NumPy

Buat vector x dengan ukuran 3x1.

In [2]:
# Buat vector x dengan ukuran 3x1
x = np.array([[1],
              [2],
              [3]])
print('Vector x (3x1):')
print(x)

Vector x (3x1):
[[1]
 [2]
 [3]]


In [3]:
# Hitung panjang vector x
panjang_x = len(x)
print('Panjang vector x:', panjang_x)

Panjang vector x: 3


In [4]:
# Tampilkan ukuran vector x
print('Ukuran vector x (shape):', x.shape)

Ukuran vector x (shape): (3, 1)


In [5]:
# Tampilkan tipe data dari vector x
print('Tipe data vector x:', type(x))
print('Dtype elemen:', x.dtype)

Tipe data vector x: <class 'numpy.ndarray'>
Dtype elemen: int64


In [6]:
# Akses elemen pertama dari vector x
elemen_pertama = x[0]
print('Elemen pertama vector x:', elemen_pertama)

Elemen pertama vector x: [1]


In [7]:
# Tampilkan tipe data elemen pertama dari vector x
print('Tipe data elemen pertama:', type(elemen_pertama))

Tipe data elemen pertama: <class 'numpy.ndarray'>


## Soal No. 2 — Transpose Vector (NumPy)

Lakukan transpose pada vector x dan simpan pada variabel `x_t`.

In [8]:
# Lakukan transpose pada vector x
x_t = x.T
print('Transpose x_t:')
print(x_t)

Transpose x_t:
[[1 2 3]]


In [9]:
# Tampilkan ukuran dari vector x_t
print('Ukuran x_t:', x_t.shape)

Ukuran x_t: (1, 3)


In [10]:
# Buat vector y dan lakukan transpose, simpan pada variabel y_t
y = np.array([[4],
              [5],
              [6]])
y_t = y.T
print('Transpose y_t:')
print(y_t)

Transpose y_t:
[[4 5 6]]


In [11]:
# Tampilkan ukuran dari vector y_t
print('Ukuran y_t:', y_t.shape)

Ukuran y_t: (1, 3)


## Soal No. 3 — Transpose dengan PyTorch dan TensorFlow

In [12]:
# ======== PyTorch ========
x_pt = torch.tensor([[1.0], [2.0], [3.0]])
x_t_pt = x_pt.T
print('Vector x (PyTorch):')
print(x_pt)
print('Transpose x_t (PyTorch):')
print(x_t_pt)
print('Ukuran x_t PyTorch:', x_t_pt.shape)

Vector x (PyTorch):
tensor([[1.],
        [2.],
        [3.]])
Transpose x_t (PyTorch):
tensor([[1., 2., 3.]])
Ukuran x_t PyTorch: torch.Size([1, 3])


In [13]:
y_pt = torch.tensor([[4.0], [5.0], [6.0]])
y_t_pt = y_pt.T
print('Transpose y_t (PyTorch):')
print(y_t_pt)
print('Ukuran y_t PyTorch:', y_t_pt.shape)

Transpose y_t (PyTorch):
tensor([[4., 5., 6.]])
Ukuran y_t PyTorch: torch.Size([1, 3])


In [14]:
# ======== TensorFlow ========
x_tf = tf.constant([[1.0], [2.0], [3.0]])
x_t_tf = tf.transpose(x_tf)
print('Vector x (TensorFlow):')
print(x_tf)
print('Transpose x_t (TensorFlow):')
print(x_t_tf)
print('Ukuran x_t TensorFlow:', x_t_tf.shape)

Vector x (TensorFlow):
tf.Tensor(
[[1.]
 [2.]
 [3.]], shape=(3, 1), dtype=float32)
Transpose x_t (TensorFlow):
tf.Tensor([[1. 2. 3.]], shape=(1, 3), dtype=float32)
Ukuran x_t TensorFlow: (1, 3)


In [15]:
y_tf = tf.constant([[4.0], [5.0], [6.0]])
y_t_tf = tf.transpose(y_tf)
print('Transpose y_t (TensorFlow):')
print(y_t_tf)
print('Ukuran y_t TensorFlow:', y_t_tf.shape)

Transpose y_t (TensorFlow):
tf.Tensor([[4. 5. 6.]], shape=(1, 3), dtype=float32)
Ukuran y_t TensorFlow: (1, 3)
