# SUBBAB 10: Matrix Tensors

Topik ini membahas tentang **matrix** — tensor 2 dimensi (rank 2).

Matrix berukuran **m x n** artinya memiliki **m baris** dan **n kolom**.

In [1]:
import numpy as np
import torch
import tensorflow as tf

## Soal No. 1 — NumPy

Buat matrix X berukuran 2x3 menggunakan NumPy.

In [2]:
# Buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[1, 2, 3],
              [4, 5, 6]])
print('Matrix X (2x3):')
print(X)

Matrix X (2x3):
[[1 2 3]
 [4 5 6]]


In [3]:
# Tampilkan ukuran dari matrix X
print('Ukuran matrix X (shape):', X.shape)

Ukuran matrix X (shape): (2, 3)


In [4]:
# Tampilkan seluruh elemen dari kolom pertama matrix X
kolom_pertama = X[:, 0]
print('Kolom pertama matrix X:', kolom_pertama)

Kolom pertama matrix X: [1 4]


In [5]:
# Tampilkan seluruh elemen dari baris kedua matrix X
baris_kedua = X[1, :]
print('Baris kedua matrix X:', baris_kedua)

Baris kedua matrix X: [4 5 6]


## Soal No. 2 — PyTorch

Ulangi soal nomor 1 menggunakan PyTorch.

In [6]:
# Buat matrix X berukuran 2x3 menggunakan PyTorch
X_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])
print('Matrix X (PyTorch):')
print(X_pt)

Matrix X (PyTorch):
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
# Tampilkan ukuran dari matrix X
print('Ukuran matrix X (shape):', X_pt.shape)

Ukuran matrix X (shape): torch.Size([2, 3])


In [8]:
# Tampilkan seluruh elemen dari kolom pertama
print('Kolom pertama:', X_pt[:, 0])

Kolom pertama: tensor([1, 4])


In [9]:
# Tampilkan seluruh elemen dari baris kedua
print('Baris kedua:', X_pt[1, :])

Baris kedua: tensor([4, 5, 6])


## Soal No. 2 (lanjutan) — TensorFlow

Ulangi soal nomor 1 menggunakan TensorFlow.

In [10]:
# Buat matrix X berukuran 2x3 menggunakan TensorFlow
X_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6]])
print('Matrix X (TensorFlow):')
print(X_tf)

Matrix X (TensorFlow):
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [11]:
# Tampilkan ukuran dari matrix X
print('Ukuran matrix X (shape):', X_tf.shape)

Ukuran matrix X (shape): (2, 3)


In [12]:
# Tampilkan seluruh elemen dari kolom pertama
print('Kolom pertama:', X_tf[:, 0])

Kolom pertama: tf.Tensor([1 4], shape=(2,), dtype=int32)


In [13]:
# Tampilkan seluruh elemen dari baris kedua
print('Baris kedua:', X_tf[1, :])

Baris kedua: tf.Tensor([4 5 6], shape=(3,), dtype=int32)
