# SUBBAB 12: Exercises on Algebra Data Structures

Soal latihan untuk menguji pemahaman tentang struktur data aljabar linier.

In [1]:
import numpy as np
import torch
import tensorflow as tf

## Soal No. 1 — What is the transpose of this vector?

Diketahui vector kolom:
$$v = \begin{bmatrix} 25 \\ 2 \\ -3 \\ -25 \end{bmatrix}$$

Tentukan transpos dari vector tersebut!

### Jawaban — NumPy

In [2]:
# Definisikan vector v sebagai column vector (4x1)
v = np.array([[25],
              [2],
              [-3],
              [-25]])
print('Vector v (4x1):')
print(v)
print('Shape v:', v.shape)

Vector v (4x1):
[[ 25]
 [  2]
 [ -3]
 [-25]]
Shape v: (4, 1)


In [3]:
# Transpose vector v -> menjadi row vector (1x4)
v_T = v.T
print('Transpose v^T (1x4):')
print(v_T)
print('Shape v^T:', v_T.shape)

Transpose v^T (1x4):
[[ 25   2  -3 -25]]
Shape v^T: (1, 4)


### Jawaban — PyTorch

In [4]:
# Definisikan vector v menggunakan PyTorch
v_pt = torch.tensor([[25],
                     [2],
                     [-3],
                     [-25]], dtype=torch.float32)
print('Vector v (PyTorch):')
print(v_pt)
print('Shape v:', v_pt.shape)

Vector v (PyTorch):
tensor([[ 25.],
        [  2.],
        [ -3.],
        [-25.]])
Shape v: torch.Size([4, 1])


In [5]:
# Transpose dengan PyTorch
v_T_pt = v_pt.T
print('Transpose v^T (PyTorch):')
print(v_T_pt)
print('Shape v^T:', v_T_pt.shape)

Transpose v^T (PyTorch):
tensor([[ 25.,   2.,  -3., -25.]])
Shape v^T: torch.Size([1, 4])


### Jawaban — TensorFlow

In [6]:
# Definisikan vector v menggunakan TensorFlow
v_tf = tf.constant([[25],
                    [2],
                    [-3],
                    [-25]], dtype=tf.float32)
print('Vector v (TensorFlow):')
print(v_tf)
print('Shape v:', v_tf.shape)

Vector v (TensorFlow):
tf.Tensor(
[[ 25.]
 [  2.]
 [ -3.]
 [-25.]], shape=(4, 1), dtype=float32)
Shape v: (4, 1)


In [7]:
# Transpose dengan TensorFlow
v_T_tf = tf.transpose(v_tf)
print('Transpose v^T (TensorFlow):')
print(v_T_tf)
print('Shape v^T:', v_T_tf.shape)

Transpose v^T (TensorFlow):
tf.Tensor([[ 25.   2.  -3. -25.]], shape=(1, 4), dtype=float32)
Shape v^T: (1, 4)


### Kesimpulan

Transpose dari vector kolom $v$ berukuran **(4×1)** adalah vector baris $v^T$ berukuran **(1×4)**:

$$v^T = \begin{bmatrix} 25 & 2 & -3 & -25 \end{bmatrix}$$